spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:h2:mem:inventorydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8082

springdoc:
  api-docs:
    path: /inventory/v3/api-docs
