spring:
  application:
    name: order-service

  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081


springdoc:
  api-docs:
    path: /order/v3/api-docs
  



resilience4j:
  retry:
    instances:
      paymentRetry:
        max-attempts: 3
        wait-duration: 2s

      inventoryRetry:
        max-attempts: 3
        wait-duration: 1s

  circuitbreaker:
    instances:
      paymentCircuitBreaker:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

      inventoryCircuitBreaker:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s





eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    



        

